[phases.setup]
nixPkgs = ['...', 'postgresql']

[phases.build]
cmds = [
  'npm run build:css',
  'python manage.py collectstatic --no-input --clear'
]

[start]
cmd = 'gunicorn config.wsgi --log-file -'
