[phases.setup]
nixPkgs = ['python312', 'postgresql']

[phases.build]
cmds = [
  'npm run build:css',
  'python3.12 manage.py collectstatic --no-input --clear'
]

[start]
cmd = 'gunicorn config.wsgi --log-file -'
