[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "nodejs", "postgresql"]

[phases.install]
cmds = [
  "npm install",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build:css",
  "python manage.py collectstatic --no-input --clear"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"