from django.urls import path
from . import views

urlpatterns = [
    path('', views.league_selection, name='league_selection'),
    path('get_seasons/<int:league_id>/', views.get_seasons_for_league, name='get_seasons_for_league'),
    path('league/<int:league_id>/<int:season_id>/', views.league_home, name='league_home'),
    path('league/<int:league_id>/<int:season_id>/teams/', views.team_list, name='team_list'),
    path('league/<int:league_id>/<int:season_id>/matchdays/', views.league_matchday_list, name='league_matchday_list'),
    path('league/<int:league_id>/<int:season_id>/standings/', views.league_standings_view, name='league_standings_view'),
    path('league/<int:league_id>/<int:season_id>/leaderboard/', views.leaderboard_view, name='leaderboard_view'),
    path('tournament/<int:tournament_id>/<int:season_id>/', views.tournament_home, name='tournament_home'),
    path('tournament/<int:tournament_id>/<int:season_id>/teams/', views.tournament_teams, name='tournament_teams'),
    path('tournament/<int:tournament_id>/<int:season_id>/matchdays/', views.tournament_matchdays, name='tournament_matchdays'),
    path('tournament/<int:tournament_id>/<int:season_id>/matchday/<int:matchday_id>/', views.tournament_matchday_detail, name='tournament_matchday_detail'),
    path('tournament/<int:tournament_id>/<int:season_id>/standings/', views.tournament_standings, name='tournament_standings'),
    path('tournament/<int:tournament_id>/<int:season_id>/leaderboard/', views.tournament_leaderboard, name='tournament_leaderboard'),
    path('matchday/<int:matchday_id>/', views.matchday_detail, name='matchday_detail'),
    path('match/<int:match_id>/stats/', views.match_statistics, name='match_statistics'),
    path('match/<int:match_id>/roster/', views.match_roster_view, name='match_roster_view'),
    path('match/<int:match_id>/roster/update/', views.update_roster_view, name='update_roster_view'),
    path('tournament_match/<int:tournament_id>/<int:season_id>/<int:match_id>/stats/', views.tournament_match_statistics, name='tournament_match_statistics'),
    path('team/<int:team_id>/', views.team_detail, name='team_detail'),
    path('team/<int:team_id>/player/add/', views.player_form_view, name='player_add'),
    path('team/<int:team_id>/player/<int:player_id>/edit/', views.player_form_view, name='player_edit'),
    path('tournament_team/<int:tournament_id>/<int:season_id>/<int:team_id>/', views.tournament_team_detail, name='tournament_team_detail'),
    path('tournament_team/<int:tournament_id>/<int:season_id>/<int:team_id>/player/add/', views.player_form_view, name='tournament_player_add'),
    path('tournament_team/<int:tournament_id>/<int:season_id>/<int:team_id>/player/<int:player_id>/edit/', views.player_form_view, name='tournament_player_edit'),
    path('player/<int:player_id>/', views.player_detail, name='player_detail'),
]
