# Generated by Django 5.2.3 on 2025-07-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0002_alter_match_options_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistic',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
