# Generated by Django 5.2.3 on 2025-07-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0003_playerstatistic_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolapp.season')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teams', models.ManyToManyField(to='futbolapp.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolapp.tournament')),
            ],
            options={
                'unique_together': {('name', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_away_matches', to='futbolapp.team')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolapp.group')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_home_matches', to='futbolapp.team')),
            ],
            options={
                'verbose_name_plural': 'Tournament Matches',
                'ordering': ['date'],
                'unique_together': {('group', 'home_team', 'away_team')},
            },
        ),
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolapp.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolapp.team')),
            ],
            options={
                'unique_together': {('group', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('clean_sheets', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('present', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolapp.player')),
                ('tournament_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolapp.tournamentmatch')),
            ],
            options={
                'unique_together': {('player', 'tournament_match')},
            },
        ),
    ]
