# Generated by Django 5.2.3 on 2025-07-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0005_remove_tournament_season_matchday_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
