# Generated by Django 5.0.14 on 2025-07-04 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0007_team_tournament_alter_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='matchday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='futbolapp.matchday'),
        ),
    ]
