# Generated by Django 5.0.14 on 2025-07-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0008_tournamentmatch_matchday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentmatch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='match_type',
            field=models.CharField(choices=[('group_stage', 'Group Stage'), ('quarter_final', 'Quarter-Final'), ('semi_final', 'Semi-Final'), ('final', 'Final'), ('third_place', '3rd Place Match')], default='group_stage', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='futbolapp.group'),
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='matchday',
        ),
    ]
