# Generated by Django 5.0.14 on 2025-09-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0010_referee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referee',
            name='user',
        ),
    ]
