# Generated by Django 5.0.14 on 2025-11-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0011_remove_referee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('max_players', models.IntegerField(default=10)),
                ('current_players', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
