# Generated by Django 5.0.14 on 2025-11-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0012_pickupgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupgame',
            name='price',
            field=models.IntegerField(default=4.5),
        ),
    ]
