# Generated by Django 5.0.14 on 2025-11-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0013_pickupgame_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupgame',
            name='price',
            field=models.FloatField(default=4.5),
        ),
        migrations.CreateModel(
            name='PickupGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('pickup_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='futbolapp.pickupgame')),
            ],
        ),
    ]
