# Generated by Django 5.0.14 on 2026-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0015_pickupgame_end_time_and_sync_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupgameplayer',
            name='age',
        ),
        migrations.AddField(
            model_name='pickupgameplayer',
            name='player_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('genius', 'Genius')], default='intermediate', max_length=20),
        ),
    ]
