# Generated by Django 5.0.14 on 2026-09-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0016_remove_pickupgameplayer_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupgame',
            name='location_map_url',
            field=models.URLField(blank=True, default='', help_text='Paste a full HTTPS Google Maps link. Required for new games.', max_length=2048),
        ),
    ]
