# Generated by Django 5.0.14 on 2026-09-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolapp', '0017_pickupgame_location_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupgameplayer',
            name='is_waitlisted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
